name: Auto Update TV Link

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Fetch
        uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install requests # ഇത് നിർബന്ധമാണ്
      - name: Run Scraper
        run: python scraper.py
      - name: Save Updated Link
        run: |
          git config --global user.name "TV Bot"
          git config --global user.email "bot@tv.com"
          git add playlist.m3u
          git commit -m "Automatically Updated All Malayalam Channels" || exit 0
          git push
